// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hospital_backend.Persistence;

#nullable disable

namespace hospital_backend.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20240517064857_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("hospital_backend.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecordId");

                    b.Property<DateTime>("DateOfExamination")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExaminationNotes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExaminedPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsibleDoctor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExaminedPatientId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("hospital_backend.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Illnesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("hospital_backend.Models.MedicalRecord", b =>
                {
                    b.HasOne("hospital_backend.Models.Patient", "ExaminedPatient")
                        .WithMany()
                        .HasForeignKey("ExaminedPatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExaminedPatient");
                });
#pragma warning restore 612, 618
        }
    }
}
